# Generated by Django 5.1.4 on 2024-12-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_remove_coverimage_blog_blog_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('update_title', 'Can update the title of the blog'), ('update_content', 'Can update the content of the blog')]},
        ),
    ]
